version: "3"
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '82:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    # expose:
    #   - '81'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

networks:
  default:
    name: nginx-proxy
    external: true
    
volumes:
    data: 
    letsencrypt:   