version: "3"
volumes:
  app:
  config:  
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "81:80/tcp"
    environment:
      TZ: 'Asia/Jerusalem'
      WEBPASSWORD: 'Ss@56243971'
    volumes:
      - app:/etc/pihole/
      - config:/etc/dnsmasq.d/
      
    restart: unless-stopped



